spring.application.name=gisapp

# Connect to db in Docker
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/gis_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Flyway properties
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

# Sql logging format
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true