spring.application.name=gisapp

# Connect to db in Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/gis_db
spring.datasource.username=postgres
spring.datasource.password=supersecretpassword

# Flyway properties
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# Sql logging format
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true